# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.davinci-cdex
extension:
  - url: >-
      http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: 'http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm'
    valueInteger: 2
canonical: http://hl7.org/fhir/us/davinci-cdex
name: DaVinciCDex
title: Da Vinci Clinical Data Exchange (CDex)
status: active

publisher:
  name: HL7 International - Patient Care Work Group
  url: 'http://www.hl7.org/Special/committees/patientcare'
  email: patientcare@lists.HL7.org

jurisdiction: 'urn:iso:std:iso:3166#US'
copyright: >-
  Used by permission of HL7 International all rights reserved Creative Commons License
description: >-
  This IG provides detailed guidance that helps implementers use FHIR-based interactions to support specific exchanges of clinical data between providers and payers (or other providers).
license: CC0-1.0
date: '2023-01-31'
version: 2.0.0
fhirVersion: 4.0.1
dependencies:
  hl7.fhir.us.core:
    uri: 'http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core'
    version: 3.1.1
    id: uscore
  hl7.fhir.us.davinci-hrex:
    uri: 'http://hl7.org/fhir/us/davinci-hrex/ImplementationGuide/hl7.fhir.us.davinci-hrex'
    version: 1.0.0
    id: hrex
  hl7.fhir.us.davinci-pas:
    uri: 'http://hl7.org/fhir/us/davinci-pas/ImplementationGuide/hl7.fhir.us.davinci-pas'
    version: 1.2.0-ballot
    id: pas
  hl7.fhir.us.carin-bb:
    uri: 'http://hl7.org/fhir/us/carin-bb/ImplementationGuide/hl7.fhir.us.carin-bb'
    version: 2.0.0
    id: c4bb
  hl7.fhir.us.davinci-dtr:
    uri: 'http://hl7.org/fhir/us/davinci-dtr/ImplementationGuide/hl7.fhir.us.davinci-dtr'
    version: 1.1.0-ballot
    id: dtr
  hl7.fhir.uv.sdc:
    uri: 'http://hl7.org/fhir/uv/sdc/ImplementationGuide/hl7.fhir.uv.sdc'
    version: 3.0.0
    id: sdc

# Groups can control certain aspects of the IG generation.  The IG
# documentation recommends that authors use the default groups that
# are provided by the templating framework, but if authors want to
# use their own instead, they can use the mechanism below.  This will
# create IG.definition.grouping entries and associate the individual
# resource entries with the corresponding groupIds.
groups:
  AttachmentsProfiles:
    name: Attachments Profiles
    description: Profiles Associated with CDex Attachments Transactions
    resources:
      - StructureDefinition/cdex-task-attachment-request
      - StructureDefinition/cdex-practitionerrole
      - StructureDefinition/cdex-patient-demographics
  AttachmentsOperations:
    name: Attachments Operations
    description: Operations Associated with CDex Attachments Transactions
    resources:
      - OperationDefinition/submit-attachment
  AttachmentsTerminology:
    name: Attachments Terminology
    description: ValueSets Associated with CDex Attachments Transactions
    resources:
      - ValueSet/cdex-attachment-task-code
      - ValueSet/cdex-claim-use
  AttachmentsExamples:
    name: Attachments Examples 
    description: Examples Associated with CDex Attachments Transactions
    resources:
      - Task/cdex-task-example19
      - Task/cdex-task-example20
      - Task/cdex-task-example22
      - Task/cdex-task-example23
      - Task/cdex-task-example24
      - Task/cdex-task-example25
      - Task/cdex-task-example28
      - Task/cdex-task-example29
      - Parameters/cdex-parameters-example1
      - Parameters/cdex-parameters-example2
      - Parameters/cdex-parameters-example3
      - Parameters/cdex-parameters-example4
      - Parameters/cdex-parameters-example5
  TaskBasedProfiles:
    name: Task Based Approach Profiles
    description: Profiles Associated with CDex Task Based Approach Transactions
    resources:
      - StructureDefinition/cdex-task-data-request
  TaskBasedTerminology:
    name: Task Based Approach Terminology
    description: ValueSets Associated with CDex Task Based Approach Transactions
    resources:
      - ValueSet/cdex-work-queue
      - ValueSet/cdex-data-request-task-code
  TaskBasedExamples:
    name: Task Based Approach Examples
    description: Examples Associated with CDex Task Based Approach Transactions
    resources:
      - Task/cdex-task-example1
      - Task/cdex-task-example2
      - Task/cdex-task-example3
      - Task/cdex-task-example4
      - Task/cdex-task-example5
      - Task/cdex-task-example6
      - Task/cdex-task-example7
      - Task/cdex-task-example8
      - Task/cdex-task-example9
      - Task/cdex-task-example10
      - Task/cdex-task-example11
      - Task/cdex-task-example12
      - Task/cdex-task-example13
      - Task/cdex-task-example14
      - Task/cdex-task-example15
      - Task/cdex-task-example16
      - Task/cdex-task-example17
      - Task/cdex-task-example18
      - Task/cdex-task-example21
      - Task/cdex-task-example26
      - Task/cdex-task-example27
      - Task/cdex-task-example30
      - Task/cdex-task-example31
  SignatureProfiles:
    name: Signature Profiles
    description: Profiles Associated with CDex Signatures
    resources:
      - StructureDefinition/cdex-signature
      - StructureDefinition/cdex-signature-bundle
      - StructureDefinition/cdex-sdc-questionnaireresponse
  SignatureTerminology:
    name: Signature Terminology
    description: ValueSets Associated with CDex Signatures
    resources:
      - ValueSet/cdex-identifier-types
  SignatureExamples:
    name: Signature Examples
    description: Examples Associated with CDex Signatures (Several examples are in Task Based and Attachments Examples groupings as well)
    resources:
      - Bundle/cdex-searchset-digital-sig-example
      - Bundle/cdex-document-digital-sig-example
      - Bundle/cdex-electronic-sig-example
      - Questionnaire/cdex-questionnaire-example2
      - QuestionnaireResponse/cdex-questionnaireresponse-example3
      - QuestionnaireResponse/cdex-questionnaireresponse-example4
  CommonTerminology:
    name: Common Terminology
    description: ValueSets and CodeSystems used in both CDex Attachments and Task Based Approach Transactions
    resources:
      - ValueSet/cdex-POU
      - CodeSystem/cdex-temp
  CommonExamples:
    name: Common Examples
    description: Examples used in both CDex Attachments and Task Based Approach Transactions
    resources:
      - Questionnaire/cdex-questionnaire-example1
      - QuestionnaireResponse/cdex-questionnaireresponse-example1
      - QuestionnaireResponse/cdex-questionnaireresponse-example2
  CapabilityStatements:
    name: CDex Capability Statements
    description: The following artifacts define the specific capabilities that different types of systems are expected to have in order to comply with this implementation guide. Systems conforming to this implementation guide are expected to declare conformance to one or more of the following capability statements.
    resources:
      - CapabilityStatement/data-consumer-client
      - CapabilityStatement/data-consumer-server
      - CapabilityStatement/data-source-client
      - CapabilityStatement/data-source-server

pages:
  index.md:
    title: Home
  background.md:
  # specification.md:
  #   exchanging-clinical-data.md:
  direct-query.md:
  task-based-approach.md:
    task-based-conformance.md:
      title: Conforming to CDex Task Based Approach
  attachments.md:
    solicited-unsolicited-attachments.md:
      title: Solicited and Unsolicited Attachments
    sending-attachments.md:
    requesting-attachments-code.md:
      title: Requesting Attachments Using Attachments Codes
    requesting-attachments-questionnaire.md:
      title: Requesting Attachments Using Questionnaires
      extension:
        - url: >-
            http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
          valueCode: draft
    burden-reduction.md:
      title: Using CDex Attachments with DaVinci PAS
    attachments-conformance.md:
      title: Conforming to CDex Attachments
  signatures.md:
    signed-searchset-bundle-example.md:
    signed-document-bundle-example.md:
  security.md:
    title: Security and Privacy
  downloads.md:
  ImplementationGuide-hl7.fhir.us.davinci-cdex.md:
    title: CDex ImplementationGuide Resource
  changes.md:
    title: Change Log

parameters:
  path-resource:
    - input/resources
    - fsh-generated/resources
  path-pages:
    - input/pagecontent
    - input/intro-notes
    - fsh-generated/includes
  path-expansion-params: '../../input/_resources/exp-params.json'  # for using US ed of SNOMED
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'true'
  excludexml: 'false'
  excludejsn: 'false'
  excludettl: 'true'
  excludemap: 'true'
  excludeexample: 'true'
  generate:
    - xml
    - json
  version-comparison:
     - 1.0.0
     - 1.1.0
  suppressed-ids: '$examples'
  tabbed-snapshots: 'true'
copyrightyear: '2022+'
releaselabel: CI Build
# releaselabel: STU1.1
# releaselabel: Ballot

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: #index.html
    Introduction: index.html
    About This Guide: index.html#about-this-guide
    How to read this Guide: index.html#how-to-read-this-guide
    Credits: index.html#credits
  Background: # background.html
    About the Da Vinci Project: background.html
    What Do Payers Do with Clinical Information: background.html#what-do-payers-do-with-clinical-information
    Provider to Provider Data Exchange: background.html#provider-to-provider-data-exchange
    What Information is Needed: background.html#what-information-is-needed
    Where Does CDEX Fit in the Da Vinci Project: background.html#where-does-cdex-fit-in-the-da-vinci-project
    Workflow Overview: background.html#workflow-overview
  Direct Query: # direct-query.html
    Introduction: direct-query.html
    Benefits: direct-query.html#benefits
    Sequence Diagram: direct-query.html#sequence-diagram
    Discovery of Patient FHIR IDs: direct-query.html#discovery-of-patient-fhir-ids
    Direct Query Transaction Scenarios: direct-query.html#direct-query-transaction-scenarios
    Provenance: direct-query.html#provenance
    Signatures: direct-query.html#signatures
  Task Based Approach: #task-based-approach.html
    Introduction: task-based-approach.html
    Benefits: task-based-approach.html#benefits
    The Task Resource: task-based-approach.html#the-task-resource
    Sequence Diagram: task-based-approach.html#sequence-diagram
    Discovery of Identifiers: task-based-approach.html#discovery-of-identifiers
    Fetching the Data: task-based-approach.html#fetching-the-data
    Task Based Transaction Scenarios: task-based-approach.html#example-transactions-based-on-query-code-and-free-text-inputs
    Using Questionnaire as Task Input: task-based-approach.html#using-questionnaire-as-task-input
    When The Task Cannot Be Completed: task-based-approach.html#when-the-task-cannot-be-completed
    Polling vs Subscriptions: task-based-approach.html#polling-vs-subscriptions
    Formal Authorization: task-based-approach.html#formal-authorization
    Provenance: task-based-approach.html#provenance
    Signatures: task-based-approach.html#signatures
    Conforming to CDex Task Based Approach: task-based-conformance.html
  Attachments:
    Solicited and Unsolicited Attachments: solicited-unsolicited-attachments.html
    Sending Attachments: sending-attachments.html
    Requesting Attachments Using Attachments Codes: requesting-attachments-code.html
    Requesting Attachments Using Questionnaires: requesting-attachments-questionnaire.html
    Using CDex Attachments with DaVinci PAS: burden-reduction.html
    Conforming to CDex Attachments: attachments-conformance.html
  Signatures: # signatures.html
    About Signatures: signatures.html
    The Signer: signatures.html#the-signer
    What is Signed: signatures.html#what-is-signed
    CDex Enveloped Signatures: signatures.html#cdex-enveloped-signatures
    Electronic Signatures: signatures.html#electronic-signatures
    Digital Signatures: signatures.html#digital-signatures
  Security and Privacy: security.html
  FHIR Artifacts:
    Artifacts Summary: artifacts.html
    Attachments Profiles: artifacts.html#1
    Attachments Operations: artifacts.html#2
    Attachments Terminology: artifacts.html#3
    Attachments Examples: artifacts.html#4
    Task Based Approach Profiles: artifacts.html#5
    Task Based Approach Terminology: artifacts.html#6
    Task Based Approach Examples: artifacts.html#7
    Signature Profiles: artifacts.html#8
    Signature Terminology: artifacts.html#9
    Signature Examples: artifacts.html#10
    Common Terminology: artifacts.html#11
    Common Examples: artifacts.html#12
    CDex Capability Statements: artifacts.html#13
  Downloads: downloads.html
  Change Log: #changes.html
    Change Log: changes.html
    Version = 2.0.0: changes.html#version--200
    Version = 2.0.0-ballot: changes.html#version--200-ballot
    Version = 1.1.0: changes.html#version--110
    Version = 1.1.0-ballot: changes.html#version--110-ballot
    Version = 1.0.0: changes.html#version--100
    Version = 0.2.0: changes.html#version--020
    Version = 0.1.0: changes.html#version--010
