resourceType: ValueSet
id: cdex-claim-use
url: 'http://hl7.org/fhir/us/davinci-cdex/ValueSet/claim-use'
name: CDexClaimUseCodes
title: CDex Claim Use Value Set
status: active
date: '2022-06-13'
description: "The purpose of a Claim resource and the reason for attachments. Consist of the codes 'preauthorization' and 'claim'."
compose:
  include:
    - system: 'http://hl7.org/fhir/claim-use'
      concept:
        - code: claim
        - code: preauthorization
