# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.davinci-cdex
canonical: http://hl7.org/fhir/us/davinci-cdex
name: DaVinciCDex
title: Da Vinci Clinical Data Exchange (CDex) Implementation Guide
status: active
publisher:
  name: HL7 International - Patient Care Work Group
  url: 'http://www.hl7.org/Special/committees/patientcare/index.cfm'
jurisdiction: 'urn:iso:std:iso:3166#US'
copyright: >-
  Used by permission of HL7 International all rights reserved Creative Commons License
description: >-
  This IG provides detailed guidance that helps implementers use FHIR-based interactions and resources relevant to scenarios associated with Provider exchange of clinical information with Payers. The IG covers six specific use cases that demonstrate how to exchange clinical data generated by Providers with Payers and other Providers to improve care coordination, support risk adjustment, ease quality management, facilitate claims auditing and confirm medical necessity, improve member experience, and support orders and referrals. It supplies guidance on how to reuse existing profiles fit for this type of exchange and provides additional profiles and guidance to  address the requirements not covered by existing Implementation Guides and profiles.
license: CC0-1.0
date: 2020-10-01
version: 0.2.0
fhirVersion: 4.0.1
dependencies:
  hl7.fhir.us.core: 3.1.1
  hl7.fhir.us.davinci-hrex: 0.2.0
parameters:
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'true'
  excludexml: 'true'
  excludejsn: 'false'
  excludettl: 'true'
  excludemap: 'true'
  excludeexample: 'true'
  generate: [xml, json]
copyrightyear: '2020+'
releaselabel: CI Build


# ╭─────────────────────────────────────────────ig.ini─────────────────────────────────────────────╮
# │  To use a provided ig-data/ig.ini file, delete the "template" property below.                  │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
template: hl7.davinci.template#current

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Framework:
      Introduction: framework-introduction.html
      Direct Query: direct-query.html
      Using Task: using-task.html
      Using Subscriptions: using-subscriptions.html
  Use Cases:
      Improving Care Coordination: improving-care-coordination.html
      Building Accurate Risk Profiles and Health Records: building-accurate-risk-profiles.html
      Supporting Quality Management: support-quality-management.html
      Confirming Medical Necessity: confirming-medical-necessity.html
      Improving Member Experience: improving-member-experience.html
      Tracking Referrals and Orders: tracking-referrals-and-orders.html
  #Table of Contents: toc.html
  FHIR Artifacts:
      Profiles: profiles.html
      Terminology: terminology.html
      CapabilityStatements: capabilitystatements.html
  Examples: examples.html
  Downloads: downloads.html
